# Generated by Django 5.2.8 on 2025-12-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_coachcomment_rating_coachcomment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coach',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coach',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='coachcomment',
            name='type',
            field=models.CharField(choices=[('inquiry', 'استفسار'), ('previous_member', 'مشترك سابق'), ('current_member', 'مشترك حالي')], default='inquiry', max_length=20),
        ),
    ]
